stages:
  - test
  - reports

unit-test-job:
  stage: test
  script:
    - mvn clean test

allure-reports:
  stage: reports
  script:
    - allure serve
  artifacts:
    paths:
      - allure-results

